### ISSUE TITLE
Create relaton-model-ccsds

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-model-ccsds#1]
Needed for this https://github.com/relaton/relaton-ccsds/issues/1

**Comment by andrew2net** [comment]
@ronaldtse check the model please

**Comment by ronaldtse** [comment]
Will do. Thanks!

**Comment by ronaldtse** [comment]
Do we need to model the Silver Books (historical publications) as a type as well?

**Comment by andrew2net** [comment]
@ronaldtse I think if Silver Book means retired then it's a status, not a type, isn't it?

**Comment by ronaldtse** [comment]
But notice that these are slightly different when you cite it:
* `CCSDS 101.0-B-1-S` => Silver Book
* `CCSDS 101.0-B-1` => Blue Book (even though it is retired, but when it was cited it was not retired)

We don't want a document that is cited in an older document to suddenly have a different "book type" and a different "identifier" when it is now resolved.

I think we should have an additional value for Silver Book.

**Comment by andrew2net** [comment]
> We don't want a document that is cited in an older document to suddenly have a different "book type" and a different "identifier" when it is now resolved.

It will be the same type as before it was retired but different status. And we can return any identifier we need, even two identifiers.

**Comment by ronaldtse** [comment]
But the identifier and book type are different. We still need to assign it as a "Silver Book". I think it's better we separate them.

How about this?

* The "CCSDS 101.0-B-1" entry will have a "retired status" but it is a Blue Book, and will have a relationship to "CCSDS 101.0-B-1-S" as the successor.

* The "CCSDS 101.0-B-1-S" entry will have a "retired status" as a Silver Book, and will have a relationship to "CCSDS 101.0-B-1" as the predecessor.

**Comment by andrew2net** [comment]
We must create two items for each Silver Book document, right? LGTM

**Comment by andrew2net** [comment]
There are 3 Silver Book documents with unusual IDs:
CCSDS 133.1-B-1 Pre-Corrigendum 1
CCSDS 401.0-B-25s
CCSDS 701.00-R-3 (Red Book)

I guess "CCSDS 401.0-B-25s" could be transformed to "CCSDS 401.0-B-25" as a predecessor, but how to handle the other two?

**Comment by ronaldtse** [comment]
> We must create two items for each Silver Book document, right? LGTM

Yes.

> unusual IDs

Should we delegate these ID issues to pubid-ccsds?

The source data ID issues are here:
* https://github.com/relaton/relaton-data-ccsds/issues

e.g.
* https://github.com/relaton/relaton-data-ccsds/issues/7
* https://github.com/relaton/relaton-data-ccsds/issues/8
* https://github.com/relaton/relaton-data-ccsds/issues/10

**Comment by andrew2net** [comment]
> Should we delegate these ID issues to pubid-ccsds?

I don't think the pubid-ccsds can solve the problem. These IDs are from Silver Books. We need to create predecessor relations for the documents. For other IDs we just need to remove "-S" suffixes from IDs. How to create a predecessor's document ID if there is no "-S" suffix?
Could CCSDS fix the IDs?

**Comment by ronaldtse** [comment]
@andrew2net I've reported the issues to CCSDS but don't know how long it would take for them to fix.

In https://github.com/relaton/relaton-data-ccsds/issues I have listed out all the necessary ID fixes, so if you can just map them it would be sufficient.

They are:
* https://github.com/relaton/relaton-data-ccsds/issues/2
* https://github.com/relaton/relaton-data-ccsds/issues/3
* https://github.com/relaton/relaton-data-ccsds/issues/4
* https://github.com/relaton/relaton-data-ccsds/issues/5
* https://github.com/relaton/relaton-data-ccsds/issues/6
* https://github.com/relaton/relaton-data-ccsds/issues/7
* https://github.com/relaton/relaton-data-ccsds/issues/8
* https://github.com/relaton/relaton-data-ccsds/issues/10

**Comment by andrew2net** [comment]
@ronaldtse there are duplicates in the data source:
- `CCSDS 720.4-Y-1` 2 docs look identical.
- `CCSDS 720.5-Y-1` 2 docs look identical.
- `CCSDS 720.6-Y-1` 2 docs look identical.
- `CCSDS 401.0-B-S` there are 5 different docs with the ID. Looks like the ID has missed edition, but all 5 have the same edition.

The first three duplicates can be dropped, right? But the last needs to be reported to CCSDS.

**Comment by ronaldtse** [comment]
## CCSDS 720.4-Y-1, CCSDS 720.5-Y-1, CCSDS 720.6-Y-1

The first one is DOC format, the second one is PDF format
<img width="1027" alt="Screenshot 2023-08-17 at 8 02 00 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/fb8a7305-1127-4500-a982-cba11c4684e6">

## CCSDS 401.0-B-S 

This is interesting because the ID of the documents are really identical.

1994:
<img width="853" alt="Screenshot 2023-08-17 at 8 04 16 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/fe571654-d596-4cc3-b9fa-346a4b37be0a">
<img width="997" alt="Screenshot 2023-08-17 at 8 04 23 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/3aae8e0f-10f5-48dd-b13a-b059cb6dd62d">


1998:
<img width="669" alt="Screenshot 2023-08-17 at 8 04 33 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/4481a9d4-f473-4e51-97a1-57f1627117bf">
<img width="793" alt="Screenshot 2023-08-17 at 8 04 38 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/2ad2e6bd-fafb-4b70-93be-945cede11158">

1999:
<img width="677" alt="Screenshot 2023-08-17 at 8 04 55 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/7cda6da5-61a1-4c0a-af3b-c045c5a1010b">
<img width="778" alt="Screenshot 2023-08-17 at 8 05 01 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/dd7bd847-2fc5-4ffe-bd67-69d8585964a5">

2000:
<img width="651" alt="Screenshot 2023-08-17 at 8 05 11 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/c1ca585a-ee3d-4395-9dfa-c27c08d315ff">
<img width="776" alt="Screenshot 2023-08-17 at 8 05 23 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/e6e701b9-9276-44f9-86be-9bce9e9b4192">

2001:
<img width="648" alt="Screenshot 2023-08-17 at 8 05 43 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/ae3ee3c5-9942-4b51-9ffc-38a81ebd400c">
<img width="774" alt="Screenshot 2023-08-17 at 8 05 50 PM" src="https://github.com/relaton/relaton-model-ccsds/assets/11865/2701be40-23b4-4036-b41a-8f35b2d5a25e">

We will have to report this to CCSDS to find out the proper solution.

**Comment by andrew2net** [comment]
> The first one is DOC format, the second one is PDF format

@ronaldtse so I guess we should merge each pair into a single document with DOC and PDF links, right?

**Comment by ronaldtse** [comment]
> I guess we should merge each pair into a single document with DOC and PDF links, right?

@andrew2net yes I think this is the correct method.

Can you help document these decisions in the README? Thanks.

**Comment by mico** [comment]
> But the identifier and book type are different. We still need to assign it as a "Silver Book". I think it's better we separate them.
> 
> How about this?
> 
> * The "CCSDS 101.0-B-1" entry will have a "retired status" but it is a Blue Book, and will have a relationship to "CCSDS 101.0-B-1-S" as the successor.
> * The "CCSDS 101.0-B-1-S" entry will have a "retired status" as a Silver Book, and will have a relationship to "CCSDS 101.0-B-1" as the predecessor.

@ronaldtse could you clarify what is the use case for having two identical identifiers (with the difference only in retired status) that are pointing to each other?
Do we want to return identifier without retired status first?
```RelatonCcsds::Bibliography.get("CCSDS 713.5-B-1 Cor. 1")``` will return `CCSDS 713.5-B-1 Cor. 1` first, but not `CCSDS 713.5-B-1-S Cor. 1`, is that what we want?

In that case we can add test for this, right now there are no tests for use cases for this behavious.
